function createfigure(X1, Y1, X2, Y2)
%CREATEFIGURE(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 26-Feb-2013 19:16:27

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 0.5]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',1,'DisplayName','详细模型');

% Create plot
plot(X2,Y2,'Parent',axes1,'LineWidth',1,'LineStyle','--','Color',[1 0 0],...
    'DisplayName','快速仿真模型');

% Create xlabel
xlabel('t (s)');

% Create ylabel
ylabel('U_d_c (kV)');

% Create legend
legend(axes1,'show');

